# Generated by Django 3.2.6 on 2021-08-05 16:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('time_slot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='group',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='room_name',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='subject',
        ),
        migrations.AddField(
            model_name='timeslot',
            name='day',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=0),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='end_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
