# Generated by Django 3.2.6 on 2021-08-05 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='hour_count',
            field=models.IntegerField(default=0),
        ),
    ]
