# Generated by Django 3.2.6 on 2021-08-05 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='degree',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
